use_frameworks!

target 'SwiftyFormsUI_Example' do
  pod 'SwiftyFormsUI', :path => '../'

  target 'SwiftyFormsUI_Tests' do
	  inherit! :search_paths
		pod 'Quick', '~> 0.10.0'
		pod 'Nimble', '~> 5.0.0'
  end
end
